name: Main workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down Repository
        uses: actions/checkout@v4
      - name: Build application
        run: ci/build-app.sh
      - name: Testing
        run: ci/unit-test-app.sh
      - uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
